server:
  port: 6010
spring:
  application:
    name: eureka
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  server:
    enable-self-preservation: false
  client:
    registerWithEureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone:
        http://${eureka.instance.hostname}:${server.port}/eureka/
